/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Activity struct {

	// Unique identifier associated with log entry.
	Id string `json:"id,omitempty"`

	// URL to the /activities/{...} for the specific log entry.
	Url string `json:"url,omitempty"`

	// Log level of activity.
	Level string `json:"level,omitempty"`

	// Short summary describing the activity.
	Summary string `json:"summary,omitempty"`

	CreatedBy *UserReference `json:"createdBy,omitempty"`

	// Time the activity was recorded.
	CreatedDate time.Time `json:"createdDate,omitempty"`

	// Category of activity.
	Type_ string `json:"type,omitempty"`

	Source *Source `json:"source,omitempty"`
}
