/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Allocations for events and orchestration instances for the whole  Salesforce org.
type AllocationsRepresentation struct {

	MaxInstanceAllocation []ErrorUnknown `json:"maxInstanceAllocation,omitempty"`

	MaxEventAllocation []ErrorUnknown `json:"maxEventAllocation,omitempty"`
}
