/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// An allocation for the Salesforce org.
type AllocationCountRepresentation struct {

	// The value for the allocation.
	Count int32 `json:"count,omitempty"`

	// The description of the allocation.
	Description string `json:"description,omitempty"`
}
