/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Summary information about a context including system fields and excluding event and reference data information.
type ContextSummaryRepresentation struct {

	// A unique identifier for the context.
	Id string `json:"id,omitempty"`

	// A unique name that's used to refer to the context through the API.
	Name string `json:"name,omitempty"`

	// A namespace prefix used for packages.
	Namespace string `json:"namespace,omitempty"`

	// The context label that's displayed in the user interface.
	Label string `json:"label,omitempty"`

	// Resource URL to retrieve this context.
	Url string `json:"url,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedDate string `json:"createdDate,omitempty"`

	CreatedBy *UserReference `json:"createdBy,omitempty"`

	LastModifiedDate string `json:"lastModifiedDate,omitempty"`

	LastModifiedBy *UserReference `json:"lastModifiedBy,omitempty"`

	// A context description.
	Description string `json:"description,omitempty"`

	// The Salesforce IoT runtime used.
	Runtime string `json:"runtime,omitempty"`
}
