/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The definition of a context.
type ContextInputRepresentation struct {

	// A unique name that's used to refer to the context through the API.
	Name string `json:"name,omitempty"`

	// The context label that's displayed in the user interface.
	Label string `json:"label,omitempty"`

	// A description of the context.
	Description string `json:"description,omitempty"`

	// The Salesforce IoT runtime used.
	Runtime string `json:"runtime,omitempty"`

	// A list of one ore more events associated with this context.
	Events []OrchestrationEventTypeInputRepresentation `json:"events,omitempty"`

	// The Salesforce object associated with this context.
	ReferenceData []ContextDatasetInputRepresentation `json:"referenceData,omitempty"`
}
