/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// URL to Orchestrations that use the context.
type Dependencies struct {

	// URL to orchestrations that use the context.
	Orchestrations string `json:"orchestrations,omitempty"`
}
