/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A generic error with a message and status.
type ErrorRepresentation struct {

	Text string `json:"text,omitempty"`

	Severity string `json:"severity,omitempty"`
}
