/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about the event, such as the event name, label, and type.
type EventTypeReference struct {

	// The event type.
	Type_ string `json:"type,omitempty"`

	// The event label that's displayed in the user interface.
	Label string `json:"label,omitempty"`

	// A unique name that's used to refer to the event through the API.
	Name string `json:"name,omitempty"`

	// A namespace prefix used for packages.
	Namespace string `json:"namespace,omitempty"`

	// A unique identifier for the event definition.
	Id string `json:"id,omitempty"`
}
