/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MetadataActivityInfo struct {

	// Serialized representation of context or orchestration definition pre-change.
	OriginalDefinition string `json:"originalDefinition,omitempty"`

	// Serialized representation of context or orchestration definition post change.
	CurrentDefinition string `json:"currentDefinition,omitempty"`
}
