/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A validation message.
type OrchestrationValidationMessageRepresentation struct {

	// The location of the warning or error.
	Location string `json:"location,omitempty"`

	// The validation message text.
	Message string `json:"message,omitempty"`

	// Indicates whether the issue is a warning or an error.
	Severity string `json:"severity,omitempty"`
}
