/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A variable defined in an orchestration.
type OrchestrationVariableRepresentation struct {

	// A unique identifier for the variable.
	Id int32 `json:"id,omitempty"`

	// The variable name.
	Name string `json:"name,omitempty"`

	// A description of the variable.
	Description string `json:"description,omitempty"`

	// The event from which field values are used to build the variable value.
	EventSource string `json:"eventSource,omitempty"`

	// The condition to be evaluated. The Salesforce Expression Language is supported.
	Condition string `json:"condition,omitempty"`

	// An initial value for the variable.
	InitialValue string `json:"initialValue,omitempty"`

	// The data type of the variable.
	DataType string `json:"dataType,omitempty"`
}
