/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A Salesforce record field assignment in a Salesforce output action.
type OrchestrationSalesforceOutputActionField struct {

	// The field name.
	Field string `json:"field,omitempty"`

	// The field value.
	Value string `json:"value,omitempty"`
}
