/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Usage information for an orchestration.
type OrchestrationUsageRepresentation struct {

	// The orchestration activation status.
	ActivationStatus string `json:"activationStatus,omitempty"`

	// The orchestration name.
	Name string `json:"name,omitempty"`

	// The number of instances for the orchestration.
	InstanceCount int32 `json:"instanceCount,omitempty"`

	// The number of events processed successfully for the orchestration in the last 24 hours.
	ProcessedEventCount int32 `json:"processedEventCount,omitempty"`

	// The number of events skipped for the orchestration in the last 24 hours.
	RejectedEventCount int32 `json:"rejectedEventCount,omitempty"`

	// Resource URL to retrieve the orchestration.
	OrchestrationUrl string `json:"orchestrationUrl,omitempty"`
}
