/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The count of orchestration transitions from one state to another.
type OrchestrationTransitionCount struct {

	// The count of orchestration transitions from one state to another.
	Count int32 `json:"count,omitempty"`

	// The origin state.
	FromStateId int32 `json:"fromStateId,omitempty"`

	// The destination state.
	ToStateId int32 `json:"toStateId,omitempty"`
}
