/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Throttling behavior applied to a rule.
type OrchestrationRuleThrottleRepresentation struct {

	// The maximum number of times per period that the rule can be triggered.
	Times int32 `json:"times,omitempty"`

	// The period during which throttling occurs.
	Period int32 `json:"period,omitempty"`

	// The time unit associated with the period.
	Unit string `json:"unit,omitempty"`
}
