/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrchestrationSalesforceOutputActionRepresentation struct {

	Name string `json:"name,omitempty"`

	Label string `json:"label,omitempty"`

	FieldAssignments []OrchestrationSalesforceOutputActionField `json:"fieldAssignments,omitempty"`

	RecordFilters []OrchestrationSalesforceOutputActionField `json:"recordFilters,omitempty"`

	SalesforceObjectApiName string `json:"salesforceObjectApiName,omitempty"`

	ResponseEventName string `json:"responseEventName,omitempty"`
}
