/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list of orchestration usage information.
type OrchestrationUsageCollectionRepresentation struct {

	// The URL you use to get the next page of orchestration usage information.
	NextPageUrl string `json:"nextPageUrl,omitempty"`

	// Total number of usage items.
	TotalSize int32 `json:"totalSize,omitempty"`

	// A list of orchestrations and their usage information.
	Orchestrations []ErrorUnknown `json:"Orchestrations,omitempty"`
}
