/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list of orchestration activation summaries.
type OrchestrationActivationCollectionRepresentation struct {

	// The URL you use to get the next page of activations.
	NextPageUrl string `json:"nextPageUrl,omitempty"`

	// The total number of activations for this orchestration.
	TotalSize string `json:"totalSize,omitempty"`

	// Resource URL to retrieve this list of activations.
	Url string `json:"url,omitempty"`

	// A list of of orchestration activation summaries.
	Activations []OrchestrationActivationSummaryRepresentation `json:"activations"`
}
