/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrchestrationTemporalAggregationVariableValueRepresentation struct {

	EventField string `json:"eventField,omitempty"`

	TemporalWindow *SalesforceTemporalExpression `json:"temporalWindow,omitempty"`
}
