/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Summary information about an orchestration including system fields but excluding the orchestration definition.
type OrchestrationSummaryRepresentation struct {

	// A unique identifier for the orchestration.
	Id string `json:"id,omitempty"`

	// A unique name that's used to refer to the orchestration through the API.
	Name string `json:"name,omitempty"`

	// A namespace prefix used for packages.
	Namespace string `json:"namespace,omitempty"`

	// The orchestration label that's displayed in the user interface.
	Label string `json:"label,omitempty"`

	// Resource URL to retrieve this orchestration.
	Url string `json:"url,omitempty"`

	CreatedDate string `json:"createdDate,omitempty"`

	CreatedBy *UserReference `json:"createdBy,omitempty"`

	LastModifiedDate string `json:"lastModifiedDate,omitempty"`

	LastModifiedBy *UserReference `json:"lastModifiedBy,omitempty"`

	// The orchestration status.
	Status string `json:"status,omitempty"`
}
