/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrchestrationInstanceLifecycleStatus string

// List of OrchestrationInstanceLifecycleStatus
const (
	NOT_STARTED OrchestrationInstanceLifecycleStatus = "NotStarted"
	STARTED OrchestrationInstanceLifecycleStatus = "Started"
	RESTARTED OrchestrationInstanceLifecycleStatus = "Restarted"
	CURRENT OrchestrationInstanceLifecycleStatus = "Current"
	TERMINATED OrchestrationInstanceLifecycleStatus = "Terminated"
	ERRED OrchestrationInstanceLifecycleStatus = "Erred"
	DEPRECATED OrchestrationInstanceLifecycleStatus = "Deprecated"
)
