/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list containing summary information of all orchestrations.
type OrchestrationCollectionRepresentation struct {

	// The URL you use to get the next page of orchestrations.
	NextPageUrl string `json:"nextPageUrl,omitempty"`

	// A list of orchestration summaries returned per page.
	Orchestrations []OrchestrationSummaryRepresentation `json:"orchestrations"`
}
