/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A reference to an orchestration state.
type OrchestrationStateReferenceRepresentation struct {

	// A unique identifier for the state.
	Id int32 `json:"id,omitempty"`

	// The state name.
	Name string `json:"name,omitempty"`
}
