/*
 * Salesforce IoT API
 *
 * Use the Salesforce IoT REST API to create and manage orchestrations and contexts, and retrieve usage data.
 *
 * API version: 43.0.0
 * Contact: support@salesforce.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// An orchestration variable.
type VariableRepresentation struct {

	// The variable name.
	Name string `json:"name,omitempty"`

	// The variable value.
	Value *interface{} `json:"value,omitempty"`

	// The variable type.
	DataType string `json:"dataType,omitempty"`
}
